### PR TITLE
1.20.1

### PR DESCRIPTION
**Pull request by R2bEEaton**

### CODE REVIEW

**Comment by R2bEEaton** [comment]
Updated to 1.20.1, @lucaargolo

**Comment by Eejit43** [comment]
Amazing, it would be great to have this merged @lucaargolo!!!!

**Comment by thcrt** [comment]
Would you be able to release this to Modrinth, or at least on here as a `.jar`? :)

**Comment by ItsReptile** [comment]
@R2bEEaton do you happen to remember why did you close this and deleted the head repo? I tried to download the repo and build it, minecraft runs succesfully but crashes after a while or when i open the map. I'm not a mod dev of any sorts, just a CS student, I have 0 knowledge about this, would love an answer if you don't mind tho, please and sorry for annoying you.
https://mclo.gs/FVbZhny

**Comment by R2bEEaton** [comment]
@ItsReptile Hi! Sorry, I don't remember _why_ I deleted the repo, but I was able to find it on my PC! I have re-uploaded it here inside my "Minecraft" organization: [https://github.com/R2bEEaton-Minecraft/accurate-maps](https://github.com/R2bEEaton-Minecraft/accurate-maps).

As for the update, I also am not a very good Minecraft mod developer and at the time was a CS student as well! I updated this for a friend of mine and I don't entirely remember whether it even worked. Please clone my repo and build it and let me know if everything works as expected! **Don't just leave and leave other people with even more questions when they read this!** You can also check the commit history to see what I haphazardly changed (without really knowing what I was doing).

[I also made a new PR on this repo here](https://github.com/lucaargolo/accurate-maps/pull/14) so that hopefully it can continue to be at least a little useful to people who visit this in the future. The new PR also includes an archive containing a `.jar` file, but this is untested by me because I don't have time. Again, let us know how it goes!

Edit: Please ignore #13, I need to get better at git / GitHub lol.

**Comment by disneyritozx** [comment]
any change you update it to 1.21?

**Pull request closed without merging**
